### PR TITLE
clickOnCurrentDay -> clickOnNextWeekday

### PR DESCRIPTION
**Pull request by ibacher**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ibacher isn't simpler and more logical to set the true value for includeWeekend, right within the test?

**Comment by ibacher** [comment]
@dkayiwa I actually think this is the better solution for the Selenium tests. Otherwise, we'd have to either:

1. Write a flow to set the GP through the UI
2. Make a REST service call

Which makes the success of this test dependent on those ones. And in either of those cases, the test could still fail because of gremlins, e.g., if another test run adjusts the setting on the QA server while the test is being run.

I'm not opposed to the idea. I just don't think I could implement it in 5 minutes 😁.

**Comment by dkayiwa** [comment]
Sounds fair enough. :)
Does it help to add a comment explaining why we are using clickOnNextWeekday?

**Comment by sherrif10** [comment]
Thanks  alot @ibacher . So ideally this  will override functionality of picking days before Friday without manually setting the GP in UI!

**Pull request merged**
