### PR TITLE
Resolving atlas version to be updated with the current minor version …

### PR DESCRIPTION
**Pull request by sherrif10**
…in atlas module
cc @dkayiwa  @mozzy11

### CODE REVIEW

**Comment by mozzy11** [comment]
@sherrif10  , the Atlas module was already in **2.3.x** ,
but you have released *2.2.x*  
this commit should be reverted  https://github.com/openmrs/openmrs-distro-referenceapplication/commit/204515c80f1c9638dfb7086dae0c7e62ed68cb07

**Comment by sherrif10** [comment]
Thanks @mozzy, my the problem at first was that i had released 2.3 and encountered semver errors. i think its impossible to revert a commit from master, because i have tried to revert that commit and am facing errors. Am still looking into it

**Comment by kdaud** [comment]
@sherrif10 does this PR still count?

**Comment by sherrif10** [comment]
thanks for this catch am not sure if the release manager need, we shall close it for now

**Pull request closed without merging**
