### PR TITLE
RATEST-257:Remove selenium legacy Tests and Pages

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-257

### CODE REVIEW

**Comment by sherrif10** [comment]
Hello @kdaud , can we get this approved since everything is in qaframework now.

**Comment by sherrif10** [comment]
cc @kdaud  kindly look through the comment above.

**Comment by kdaud** [comment]
@sherrif10 thanks for the reminder. We will have the test removed once we get all the tests into the module.

**Review by kdaud — APPROVED** [review]
cc: @dkayiwa

**Comment by kdaud** [comment]
one minor comment;
 @sherrif10 any reason why you committed these changes via your master branch?

**Comment by sherrif10** [comment]
Sorry my bad. Thanks @dkayiwa

**Pull request merged**
