### PR TITLE
RATEST-235: Handled Exceptions in the catch block Method ~ PatientCaptureVitalsPage

### PR DESCRIPTION
**Pull request by Muta-Jonathan**
## Description of what I changed
Removed try-catch blocks.........which in catch blocks returned nothing...
 After, no Exception was thrown ..in running the **CaptureVitalsTest** where the **patientCaptureVitalsPage** is implemented

But one test `checkModulesTest` was failing in IDE but passing on` Github actions and bamboo ` 

## Issue I worked on

see https://issues.openmrs.org/browse/RATEST-235

### CODE REVIEW

**Comment by Muta-Jonathan** [comment]
cc @dkayiwa @sherrif10

**Review by sherrif10 — COMMENTED** [review]
Looks Good @mut-jonathan   Did you run PatientCaptureVitalsTest and confirm this does not break anything

**Comment by Muta-Jonathan** [comment]
To my observance ......... We don't have PatientCaptureVitalsTest bt PatientCaptureVitalsPage is implemented in the CaptureVitalsTest....... which was passing locally

**Comment by sherrif10** [comment]
cc @dkayiwa  could you help us approve this test.Thanks

**Comment by dkayiwa** [comment]
@sherrif10 done!

**Review by sherrif10 — APPROVED** [review]
LGTM  Thanks  @Muta-Jonathan , Hello @dkayiwa , This looks fairly enough to be merged.

**Comment by dkayiwa** [comment]
@sherrif10 did @kdaud review and approve?

**Comment by sherrif10** [comment]
Ohh my bad, cc @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan what is the motive of removing the try catch block from the methods?

**Comment by Muta-Jonathan** [comment]
@kdaud according to java.......It is not a good practice to always leave the catch block empty... either we catch an exception or throw any message........that's Java ☝️
now According to me in Openmrs since the test does not throw any Exception....it passes whether there is a try-catch or not...
Then there is no need for them at the moment...... **reason**:" for a good quality code" it's better they are removed.

**Comment by kdaud** [comment]
> according to java.......It is not a good practice to always leave the catch block empty... either we catch an exception or throw any message........that's Java

@Muta-Jonathan are you able refer to the documentation that talks about the above?

**Comment by Muta-Jonathan** [comment]
Yes @kdaud  https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java look into that, u can look at number 7....

**Comment by Muta-Jonathan** [comment]
Even number 4 it explains

**Comment by kdaud** [comment]
@Muta-Jonathan did you build the module with the changes and the no test is failing?

**Comment by Muta-Jonathan** [comment]
@kdaud ..........before doing my changes.......I first applied my chromedriver and this **CheckModulesTest** **fails**.........
automatically......so then I performed my changes and again it was the one still failing........
bt others pass...... so it would be better for verification you clone add try to test them using Junit locally ....may be on windows cause its the one am using

**Comment by kdaud** [comment]
@Muta-Jonathan which command are are you using to run the tests?

**Comment by Muta-Jonathan** [comment]
The test failing .... i think had an issue....not related to my changes but its changes merged yet they weren't passing

**Comment by kdaud** [comment]
> but its changes merged yet they weren't passing

On master, does the test fail when you `cd openmrs-distro-referenceapplication/ui-tests` and then run `mvn clean install -DskipTests=false`?

**Comment by Muta-Jonathan** [comment]
@kdaud and @sherrif10 look in this https://pastebin.com/G3pEk9JA ui-tests are failing......even before my changes........after clone hv replaced the chromedriver and ran ui-tests bt failing...........I think @sherrif10 can throw more light on this

**Comment by kdaud** [comment]
@Muta-Jonathan do you notice the error below from the logs you have shared?

```js

Results :
 
Tests in error:
  addDiagnosisToVisitNoteTest(org.openmrs.reference.AddDiagnosisToVisitNoteTest): Expected condition failed: waiting for visibility of element located by By.id: ui-id-1 (tried for 120 second(s) with 500 milliseconds interval)(..)
  addDiagnosisToVisitNoteTest(org.openmrs.reference.AddDiagnosisToVisitNoteTest): Session ID is null. Using WebDriver after calling quit()?(..)
````
What do you say about the error ? 

If CheckModulesTest had issues don't you think would have been cited among the tests that are failing?

**Comment by Muta-Jonathan** [comment]
Ya........ That was due to Timeout in the running of the Tests

**Comment by kdaud** [comment]
@Muta-Jonathan which instance are you using to run the tests ?

**Comment by sherrif10** [comment]
These tests are all passing unless one single test checkModulesTest which is still failing bringing Nullpointer Exception. This need to be ignored first, Am wondering why it passed on github actions

**Comment by sherrif10** [comment]
However still this ticket is independent from the failing tests

**Comment by Muta-Jonathan** [comment]
Local instance.......SDK @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan  restart the server and run the tests again!

**Comment by Muta-Jonathan** [comment]
@kdaud have also tested it on QA-server .......since it automated tests and others a passing except **checkModulesTest** ...its not passing................ @sherrif10 has also tried it and **checkModulesTest** on master is also failing ........  so I think the issue is not about the changes made but that test itself ...you can try to clone the master and use  _**mvn clean install -DskipTests=false**_ in the _**openmrs-distro-referenceapplication/ui-tests**_

**Comment by kdaud** [comment]
> clone the master and use _**mvn clean install -DskipTests=false**_ in the _**openmrs-distro-referenceapplication/ui-tests**_

@Muta-Jonathan cross check the build summary [here](https://pastebin.com/9Q2i4PSJ) obtained from the home work you assigned to me.

**Comment by Muta-Jonathan** [comment]
@kdaud ....today have run three tests ...first success..... the second failure...............and now it has shown success............[three test here: Success](https://pastebin.com/S0kFnfyD)......And on the specific failing test in IDE when I ran it individually it passed...
Sorry to ask bt u can try running it like two-three tyms and see the results

**Comment by kdaud** [comment]
> And on the specific failing test in IDE when I ran it individually it passed...

Which test?

**Comment by kdaud** [comment]
@Muta-Jonathan do all tests pass the build plan with your changes?

**Comment by Muta-Jonathan** [comment]
Ya, they all pass in command line @kdaud .............and the test mentioned was **addPatientAppointmentTest**.. but am also wondering why [this test](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/545#issuecomment-926404079) passes on the command line but fails in **IDE like eclipse**..........

**Comment by Muta-Jonathan** [comment]
**As you see in Eclipse it fails at the start with a nullPointer Exception** but builds success...may be help on this @dkayiwa 

Screenshot (5)

**Comment by kdaud** [comment]
@Muta-Jonathan did you figure out what was failing the test in your IDE?

**Comment by sherrif10** [comment]
Hello @kdaud  can we concentrate on what he is trying to achieve with in this pull request.

**Comment by sherrif10** [comment]
@kdaud is there any other suggestion you would recommend  to @Muta-Jonathan to follow up

**Comment by kdaud** [comment]
> @kdaud is there any other suggestion you would recommend to @Muta-Jonathan to follow up

We would need to ensure all the existing tests are passing! @Muta-Jonathan has not responded to the comment [above](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/569#issuecomment-929890876). 

From my side all the tests are passing well both within the IDE and on command line. However, as I wait for Jonathan's response, let me look into the test being cited out by him. In the nutshell, can any one share the logs to the test via pastebin.com?

**Comment by sherrif10** [comment]
> has not yet responded to the comment [above](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/569#issuecomment-929890876).

Sure thanks

**Comment by kdaud** [comment]
@sherrif10 are you also getting the same experience as Jonathan? If yes can any one share the logs to what the test throwing via pastebin.com?

**Comment by Muta-Jonathan** [comment]
@kdaud ....... It is the same experience with @sherrif10 ...........but all the tests are passing from my side..........expect in IDE may be the problem is with the test or Windows ............let me try to share the logs of the failing test

**Comment by Muta-Jonathan** [comment]
Screenshot (7)

**Comment by Muta-Jonathan** [comment]
@kdaud @sherrif10 check the logs [here](https://pastebin.com/jabRCjf9) but those logs are without changes in the code just cloned module and updating the chrome driver and then run tests

**Comment by Muta-Jonathan** [comment]
@kdaud  I think on line 31` asserthat line is getting the testName.....or name=null which is causing a nullPointer Exception`

**Comment by kdaud** [comment]
> check the logs [here](https://pastebin.com/jabRCjf9) but those logs are without changes in the code

I quickly skimmed  through the logs and the issue is being cited out at the line below

`org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)`

Have logged a ticket at https://issues.openmrs.org/browse/RATEST-241 to catch the bug.

**Comment by Muta-Jonathan** [comment]
Thanks, @kdaud I think now this issue is ok to be merged .......about that ticket let me look into it

**Comment by kdaud** [comment]
@Muta-Jonathan worth renaming the commit message to what the changes are doing!

**Comment by Muta-Jonathan** [comment]
Thanks @kdaud have changed the commit message up

**Comment by kdaud** [comment]
@Muta-Jonathan where is the changed commit message?

**Comment by Muta-Jonathan** [comment]
Any Suggestion  on the commit message because I thought it was what i changed @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan I see the changes are within one file `PatientCaptuieVitalsPage`, does this caters for all the `UI-TESTS`?

**Comment by Muta-Jonathan** [comment]
Oh I get it let me change that @kdaud

**Comment by Muta-Jonathan** [comment]
Done the needful @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan after removing the try catch blocks from the methods, did you look into the [indention](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/c80fa89a6db73426e76e4752d26ae92d3dc29fec/ui-tests/src/test/java/org/openmrs/reference/page/PatientCaptureVitalsPage.java) of the file to ensure its properly indented?

**Comment by Muta-Jonathan** [comment]
Yes @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan take a look at the following indention and tell which of the two would you recommend. 

Option 1
```js 
public void setHeightField(String value) {
        WebElement heightField = findElement(HEIGHT_FIELD);
            heightField.clear();
            heightField.sendKeys(value);
            findElement(By.xpath("//ul[@id='formBreadcrumb']/li/ul/li[2]")).click();
    }
```
Option 2
```js
 public void setHeightField(String value) {
        WebElement heightField = findElement(HEIGHT_FIELD);
         heightField.clear();
         heightField.sendKeys(value);
         findElement(By.xpath("//ul[@id='formBreadcrumb']/li/ul/li[2]")).click();
    }
```

**Comment by Muta-Jonathan** [comment]
I think 2 is better.............
should I make it so

**Comment by kdaud** [comment]
@Muta-Jonathan all the existing files in the repo are following indention number 2

**Comment by Muta-Jonathan** [comment]
true so should I make it like `2`  @kdaud

**Comment by Muta-Jonathan** [comment]
true so should I make it like `2`  @kdaud

**Comment by kdaud** [comment]
> so should I make it like `2`

@Muta-Jonathan would be awesome to do so.

**Comment by Muta-Jonathan** [comment]
cc @kdaud

**Comment by Muta-Jonathan** [comment]
cc @dkayiwa could you help to run this test on Github actions. Thanks

**Review by kdaud — APPROVED** [review]
cc: @dkayiwa

**Pull request merged**
