### PR TITLE
O3-2996: Add billing module to openmrs distro pom file and spa config…

### PR DESCRIPTION
**Pull request by alaboso**
## Description of what I changed

This PR is to introduce the Billing and StockManagement modules to the reference application. Billing requires Stock Management as a dependency.

- Added stock management backend module
- Added billing backend module
- Added stock management frontend module
- Added billing frontend module

## Issue I worked on

see https://openmrs.atlassian.net/browse/O3-2996

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by gracepotma** [comment]
FYI @dkayiwa please note these backend modules are now coming into the RefApp - so if there are concerns with the backend, now is the time to address ;) :)

**Comment by gracepotma** [comment]
FYI folks: Amos does have a plan to decouple the billing module from the inventory module in the coming weeks.

**Review by ODORA0 — APPROVED** [review]
LGTM

**Comment by gracepotma** [comment]
> @gracepotma - that will be great. Will the module still be able to bill for services and stock (defined within/outside of the inventory) and how do we plan to keep the references to stock items?

@alaboso can you please kindly respond to @ojwanganto's good question here? We definitely need to know if this would impact the inventory workflows :)

**Comment by ebambo** [comment]
> > @gracepotma - that will be great. Will the module still be able to bill for services and stock (defined within/outside of the inventory) and how do we plan to keep the references to stock items?
> 
> @alaboso can you please kindly respond to @ojwanganto's good question here? We definitely need to know if this would impact the inventory workflows :)
> 
> In meantime @dkayiwa can you please review this PR? I want to know if you feel this is appropriate and ready to include in the RefApp release being cut this week on April 18th. :)
> 
> CC @ebambo

@gracepotma thanks for push the review of this PR. Regarding @ojwanganto comment we the plan is definitely to continue supporting any existing workflows. The decoupling is in line with the approach that is being discussed by the Interoperability squad. Happy to discuss this more on the billing squad on slack.

**Comment by nravilla** [comment]
Attempted the changes in the PR, but encountered errors preventing the start of both the stock management and billing modules. The specific error message observed in the admin is -

Module Stock Management cannot be started because it requires the following module(s): dataexchange,uicommons ${uicommonsModuleVersion},uiframework ${uiframeworkVersion},appframework ${appframeworkVersion},appui ${appuiVersion},coreapps ${coreappsVersion} Please install and start these modules first.

**Review by tendomart — APPROVED** [review]

**Comment by alaboso** [comment]
> Attempted the changes in the PR, but encountered errors preventing the start of both the stock management and billing modules. The specific error message observed in the admin is -
> 
> Module Stock Management cannot be started because it requires the following module(s): dataexchange,uicommons ${uicommonsModuleVersion},uiframework ${uiframeworkVersion},appframework ${appframeworkVersion},appui ${appuiVersion},coreapps ${coreappsVersion} Please install and start these modules first.

@nravilla  - These dependencies have been removed in this [PR](https://github.com/openmrs/openmrs-module-stockmanagement/pull/18) with only `dataexchange` and `webservices.rest` remaining. I realised we can remove dataexchange (which is used to load metadata privileges and roles) in favour of initializer. 
 @slubwama  what do you think? I will update this PR accordingly.

**Comment by dkayiwa** [comment]
@alaboso do we have the stockmanagement and billing modules on https://addons.openmrs.org/?

**Comment by dkayiwa** [comment]
@alaboso the billing module also fails to start with these errors in the logs: https://pastebin.com/tpXB42WL

**Comment by alaboso** [comment]
@ojwanganto  @dkayiwa  - I realised some changes (liquibase.xml) were not migrated to the omrs repo. The liquibase file contents are different [https://github.com/palladiumkenya/openmrs-module-kenyaEMRCashier/blob/master/omod/src/main/resources/liquibase.xml](https://github.com/palladiumkenya/openmrs-module-kenyaEMRCashier/blob/master/omod/src/main/resources/liquibase.xml) and [https://github.com/openmrs/openmrs-module-billing/blob/main/omod/src/main/resources/liquibase.xml](https://github.com/openmrs/openmrs-module-billing/blob/main/omod/src/main/resources/liquibase.xml)

@ojwanganto  - Do you have any objection to migrating the former into the main omrs repo? I ask this because redoing the liquibase would introduce errors in your already-in-prod distro

**Comment by ojwanganto** [comment]
I have no objection

**Pull request closed without merging**
