### PR TITLE
RA-1193 fix AddPastVisitTest

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@AdamGrzybkowski did you notice the merge conflicts on this?

**Comment by AdamGrzybkowski** [comment]
@dkayiwa no, thanks :) I'll resolve them tomorrow

**Comment by rkorytkowski** [comment]
Please resolve conflicts.

**Comment by AdamGrzybkowski** [comment]
@rkorytkowski done

**Pull request merged**
