### PR TITLE
Switch attachments to version 2.6.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by kdaud** [comment]
cc: @dkayiwa

**Comment by dkayiwa** [comment]
@kdaud why do you cc me?

**Comment by kdaud** [comment]
> @kdaud why do you cc me?

Wanted you to take a look at the change. Unfortunately had not seen the comment you had put on one of the sister PR otherwise I wouldn't cc you here.

**Comment by dkayiwa** [comment]
Even if i had not commented. No need to cc because i get notified when a new pull request is opened.

**Comment by kdaud** [comment]
> No need to cc because i get notified when a new pull request is opened.

I surely didn't know this !! Won't do it any more

**Comment by tendomart** [comment]
Also think the upgrade was clean and easy .

**Comment by kdaud** [comment]
Closing this commit in favor of `pull/612`

**Pull request closed without merging**
