### PR TITLE
O3-858: Adding a demo lab order entry form.

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket: https://issues.openmrs.org/browse/O3-858

### CODE REVIEW

**Review by mks-d — COMMENTED** [review]
Thanks @Ruhanga!

Shouldn't there be some extra config somewhere else that makes this form show in the O3 UI? Or that just happens?

**Review by Ruhanga — COMMENTED** [review]
Hi @mks-d, adding the form via iniz ampath forms should suffice.

**Comment by ibacher** [comment]
This seems to generate an ObsGroup instead of actual orders... while I understand this is a way many implementations have handled orders, doesn't this imply we need some kind of backend handling to turn these observations into actual orders? Otherwise, we're going to have to build a weird double logic into the frontend to display actual "Order" orders and these "Obs" orders...

**Review by reagan-meant — APPROVED** [review]

**Comment by Ruhanga** [comment]
The obsGroup is simply a ui grouping and not persisted. No actual obs is persisted by the underlying widget.

**Comment by ibacher** [comment]
Thanks @Ruhanga! I get it now.

**Pull request merged**
