### PR TITLE
RATEST-91:Failing Test:Book Request Appointment Test

### PR DESCRIPTION
**Pull request by insookwa**
I deleted the other pull request and all the changes are covered already. I have removed the @ignore   
kindly review https://issues.openmrs.org/browse/RATEST-91
@k-joseph  @kdaud

### CODE REVIEW

**Comment by kdaud** [comment]
@insookwa have you tested locally on all instances and the test is passing ?

**Comment by insookwa** [comment]
Yes @kdaud  it passes locally

**Comment by kdaud** [comment]
Waiting approval to run `actions`
cc: @k-joseph

**Comment by sherrif10** [comment]
Thanks for workin on this, Clean up the ticket naming to have clear message

**Comment by insookwa** [comment]
Hello @sherrif10 i changed the naming

**Review by sherrif10 — COMMENTED** [review]
LGTM cc @k-joseph

**Pull request closed without merging**
