### PR TITLE
Add SOAP note (structured soap note ) form json

### PR DESCRIPTION
**Pull request by CynthiaKamau**
This pr introduces the concepts used in the structured SOAP note and the soap note json schema to be used.

### CODE REVIEW

**Review by ODORA0 — APPROVED** [review]

**Review by alaboso — APPROVED** [review]

**Comment by dkayiwa** [comment]
@CynthiaKamau @alaboso when i run the changes in this pull request, i get these errors on the server: https://pastebin.com/Q069Lu3v

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau @alaboso when i run the changes in this pull request, i get these errors on the server: https://pastebin.com/Q069Lu3v

Looking into it

**Comment by CynthiaKamau** [comment]
@dkayiwa We noticed that while using openconceptlab-module-dependency-2.3.0, validation passes but using openconceptlab-module-dependency-1.2.9, validation fails. We will work on making a follow up pr to remove the concept mapping errors

**Comment by dkayiwa** [comment]
@CynthiaKamau thanks for the update. I am anxiously looking forward to test changes in the follow up pull request. 😊

**Pull request merged**
