### PR TITLE
RA-1836:Bundle SPA module into REF-APP 2.11.0

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RA-1836

cc @dkayiwa  @mozzy11

### CODE REVIEW

**Comment by mozzy11** [comment]
LGTM  

cc @dkayiwa

**Comment by dkayiwa** [comment]
Did any one test these changes locally and confirm that all is well?

**Comment by mozzy11** [comment]
@sherrif10  can you try bundling ths module on a local instance and test ??

**Comment by sherrif10** [comment]
@mozzy11  sure ,Am testing it, at first i run it but let me try testing locally

**Comment by mozzy11** [comment]
no , set up an instance of reff app 2.11.0-SNAPSHOT

**Comment by sherrif10** [comment]
ok no problem

**Comment by sherrif10** [comment]
Hey @dkayiwa @mozzy i tried running current platform 2.3.1 but falling in the above error,however i manually build the module in standalone and all if fine, this is to do with running sdk not the module, the module runs fine
cre

**Comment by sherrif10** [comment]
i have been able to successfully setup an instance but spa module doesnot start at initiation

**Comment by sherrif10** [comment]
Now sdk can run on 2.3.1 am going to test this module again on platform 2.4.0

**Comment by tendomart** [comment]
This is the log i got after rebooting  Core 2.3.1 with openmrs-module-spa  uploaded

https://pastebin.com/7JMqrkYi

**Comment by sherrif10** [comment]
Thanks @tendomart for your time in testing. 
   @dkayiwa: its time to have your word now. This can run on 2.3.1 and 2.4.0-snapshot successfully, evidence prior testing the both versions

**Comment by tendomart** [comment]
> Thanks @tendomart for your time in testing.
> @dkayiwa: its time to have your word now. This can run on 2.3.1 and 2.4.0-snapshot successfully, evidence prior testing the both versions

Any time @sherrif10

**Comment by sherrif10** [comment]
oops line 349 :Caused by: java.lang.ClassNotFoundException: org.openmrs.module.web.extension.AdministrationSectionExt, Meaning there is an error admin page in spa module, however that didnot cause its failure when i was building it manually. so i think there could be another of accessing spa pages not neccessary having its adminExtensions

**Comment by tendomart** [comment]
spa2

**Comment by tendomart** [comment]
spa1

**Comment by mozzy11** [comment]
great @tendomart   ,

**Comment by dkayiwa** [comment]
When you compile this distro, is the spa module among the output modules?

**Comment by sherrif10** [comment]
cc @dkayiwa  , Yes it among the out modules , you can take look after compiling https://pastebin.com/i0F5kYGh

**Comment by sherrif10** [comment]
Great thanks @dkayiwa @mozzy @ tendomart, qa is up and running with our spa module bundled

**Pull request merged**
