### PR TITLE
RATEST-212: Add functionality for manage provider schedules page

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-212)
Description -> Add functionality for manage provider schedules page.
The page functionality in this commit is addressing [RATEST-90](https://issues.openmrs.org/browse/RATEST-90) and [RATEST-91](https://issues.openmrs.org/browse/RATEST-91) in order to resurrect the tests in those ticket.

### CODE REVIEW

**Comment by kdaud** [comment]
Waiting for review cc: @sherrif10

**Comment by kdaud** [comment]
Waiting for review cc: @sherrif10

**Comment by sherrif10** [comment]
Do we have a functionality that clicks on the appointment date first.

**Comment by kdaud** [comment]
> Do we have a functionality that clicks on the appointment date first

Yes!

Am looking into resurrecting selenium tests in  [RATEST-90](https://issues.openmrs.org/browse/RATEST-90) and [RATEST-91](https://issues.openmrs.org/browse/RATEST-91). For these tests to pass they need the functionality in this commit to have them enter into master build

**Comment by sherrif10** [comment]
> Do we have a functionality that clicks on the appointment date first.

i meant before landing on  schedule appointment we need to click on any date from the calendar.

**Comment by kdaud** [comment]
> i meant before landing on schedule appointment we need to click on any date from the calendar.

The date is clickable when scheduling appointment.

**Review by sherrif10 — APPROVED** [review]
LGTM  cc @dkayiwa . Thanks @kdaud

**Pull request merged**
