### PR TITLE
Ratest 112 : Failing Test on firefox: AddEditAppointmentBlockTest

### PR DESCRIPTION
**Pull request by Irenyak1**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-112)

Description -> Fix add edit appointment block test, failing test on firefox

### CODE REVIEW

**Comment by sherrif10** [comment]
Thanks @Irenyak1  , LGTM cc @k-joseph

**Comment by kdaud** [comment]
For quality assurance, remove the redundant code line [here](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/530aece6433fdb069c783a198962677d605e682d/ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java#L40)
Ensure the test method[ name](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/530aece6433fdb069c783a198962677d605e682d/ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java#L39) aligns with the test method naming convention. Cross check with the existing tests methods within the `ui-tests`

**Comment by kdaud** [comment]
Well-done @Irenyak1 !
Catch my comments above!

**Comment by Irenyak1** [comment]
Sure @kdaud let me work on them straight away.

**Comment by Irenyak1** [comment]
@kdaud I have implemented the changes you advised to.

**Comment by Irenyak1** [comment]
This test runs both on headless and non headless with firefox and chrome, with just removing the @Ignore tag. This was made possible after @kdaud fixed the clickOnDay() function in this[ ticket ](https://issues.openmrs.org/browse/RATEST-156) in this [commit](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/24044561533590b62c6ada5a62aac3e1273b029d) as shown on this [line](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/24044561533590b62c6ada5a62aac3e1273b029d#diff-3120cf64f26a95852c0f6dfc3226f5bf318ade8123b4a929ab58c1458db9df05R123)

**Review by sherrif10 — APPROVED** [review]
LGTM cc @k-joseph  thanks @Irenyak1

**Pull request merged**
