### PR TITLE
updating module versions in distro

### PR DESCRIPTION
**Pull request by HerbertYiga**
Updating module versions in distro cc @mozzy11   @dkayiwa

### CODE REVIEW

**Comment by HerbertYiga** [comment]
hi @dkayiwa  a gentle request to help me look through this

**Comment by sherrif10** [comment]
Hello @HerbertYiga  do you have a jira ticket for this work ? if not we can use the one i created

**Review by ibacher — APPROVED** [review]

**Comment by HerbertYiga** [comment]
hi @ibacher  is this good for merging,

**Comment by ibacher** [comment]
@HerbertYiga I'm concerned about why the tests are failing, once that's clear, I'm happy for this to be merged

**Comment by dkayiwa** [comment]
@HerbertYiga is there a reason why you commit in upper case (Shouting)

**Comment by kdaud** [comment]
> I'm concerned about why the tests are failing, once that's clear

Am working on the fix on one of the breaking test and  in 20minutes the fix will be done. Thanks

**Comment by HerbertYiga** [comment]
> I'm concerned about why the tests are failing, once that's clear, I'm happy for this to be merged

@ibacher some green light

**Pull request merged**
