### PR TITLE
(feat) Add mental health assessment form

### PR DESCRIPTION
**Pull request by NethmiRodrigo**
This PR adds the PHQ-9 Screening Tool form.

https://openmrs.atlassian.net/browse/O3-3717

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]
LGTM! Thanks, Nethmi.

**Comment by denniskigen** [comment]
@ibacher does the `Build and Validate Configuration` check have to pass for this to be merged in?

**Comment by ibacher** [comment]
@denniskigen They definitely _should_ pass or else there's very likely something broken.

**Comment by ibacher** [comment]
In this case, the failure message is: "Form Encounter type Mental Health Assessment could not be found. Please ensure that this encountertype is either loaded by Iniz or loaded in the system before Iniz runs." So that's a pretty obvious "we're missing necessary metadata to make this form usable" issue.

**Comment by ibacher** [comment]
Yeah, if we're requiring an EncounterType it should be in the metadata.

**Comment by NethmiRodrigo** [comment]
Any idea why this might be happening @ibacher @denniskigen?
Screenshot 2024-10-10 at 11 43 08 AM

**Comment by denniskigen** [comment]
I've just rerun the tests, @NethmiRodrigo. Should be ok now.

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
