### PR TITLE
RA-788 Automating RA-718 Active Visit Edit Patient Test

### PR DESCRIPTION
**Pull request by nataliaplonka**
https://issues.openmrs.org/browse/RA-788

### CODE REVIEW

**Comment by tomaszmueller** [comment]
@nataliaplonka are the methods: isElementPresent, isAlertPresent, closeAlertAndGetItsText actually needed?

**Comment by nataliaplonka** [comment]
No :) I improved it.

**Comment by tomaszmueller** [comment]
@nataliaplonka:
I still don't see the usage of these methods in this test case. Remove them please.
However, these methods may be useful in other test cases, so, in your future automated tests, think if you can use them before removing.
Second thing: In: 'Assert.assertEquals("Today", patientDashboardPage.visitLink().getText().trim());' the assertion isn't needed. You should change it into waiting for the visitlink element.
If you pull the latest changes from upstream you should have   waitForVisitLink() function in patientDashboardPage you can use.
Third thing: In the test case steps you have patient named "John Bob Smith", while in the automation test you have "John   Bob". The gender field also doesn't seem to be filled-in(does the test work?). 

And please put assertions in at least the most important places in the test to check Expected Result.
Regards,
Tomasz Mueller

**Comment by nataliaplonka** [comment]
I removed this method and assertion, you saw this when I commuted the changes I don't know why they aren't save.

**Comment by tomaszmueller** [comment]
@nataliaplonka git sometimes does strange things and you have situations when you commit & push changes and findout they aren't there. The best way is to check in 'Files changed' tab, what changes have actually been pushed.

**Pull request merged**
