### PR TITLE
Followup commit

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RA-1818

Follow up commit for reverting platform version 2.4.0-snapshot 
 cc @dkayiwa  @mozzy11

### CODE REVIEW

**Comment by mozzy11** [comment]
thanks @sherrif10

**Comment by dkayiwa** [comment]
@sherrif10 @mozzy11 this commit message is meaningless.

**Comment by sherrif10** [comment]
Thanks @mozzy11  too  for checking on this

**Comment by sherrif10** [comment]
@dkayiwa  , thanks , i have collected its message title

**Comment by mozzy11** [comment]
@sherrif10   , he also menat the commit message not just the PR title

**Comment by dkayiwa** [comment]
He did not correct. He instead just collected. 😊

**Comment by mozzy11** [comment]
😊 haha

**Comment by sherrif10** [comment]
We are all to go now, lets pray harder qa does not fail again

**Comment by mozzy11** [comment]
qa is ok. set up succesfully

**Comment by sherrif10** [comment]
That's good news

**Comment by sherrif10** [comment]
@sherrif10  @dkayiwa   feel free to  comment as this PR  accepted and close it thanks  ,

**Pull request merged**
