### PR TITLE
3.x: Build Covid19 Form

### PR DESCRIPTION
**Pull request by basrem**

### CODE REVIEW

**Comment by tendomart** [comment]
@basrem Is this directly related to a particular ticket

**Comment by sherrif10** [comment]
Probably it's related to Mekom solution.

**Comment by basrem** [comment]
> @basrem Is this directly related to a particular ticket

Hey @tendomart it was a draft PR, thanks for the alert

**Comment by basrem** [comment]
> Probably it's related to Mekom solution. cc @reagan-meant

Hi @sherrif10 , it is indeed.

**Comment by rbuisson** [comment]
@basrem , this should prob be closed, right?

**Comment by basrem** [comment]
> @basrem , this should prob be closed, right?

Yes it most definitely should, thanks @rbuisson

**Pull request closed without merging**
