### PR TITLE
RA-1102 - Fixed AddDiagnosisToVisitNoteTest to conform with guidelines

### PR DESCRIPTION
**Pull request by tmarzeion**
This PR is response for @rkorytkowski code review from https://github.com/openmrs/openmrs-distro-referenceapplication/pull/134
There are issues with test cleanup (See AddDiagnosisToVisitNoteTest.java's tearDown() comments)
I will create ticket for that when issues.openmrs.org will wake up :)
//edit
Bug ticket: https://issues.openmrs.org/browse/RA-1197

### CODE REVIEW

**Comment by rkorytkowski** [comment]
Please resolve conflicts.

**Comment by tmarzeion** [comment]
@rkorytkowski Solved

**Comment by tmarzeion** [comment]
@rkorytkowski Solved again

**Comment by rkorytkowski** [comment]
All good. Please resolve conflicts again and merge! (you should have privileges now, check https://github.com/openmrs/openmrs-distro-referenceapplication/invitations if not)

**Pull request merged**
