### PR TITLE
RATEST-91:Failing Test: Book Request Appointment Test

### PR DESCRIPTION
**Pull request by insookwa**
The test passes very well with only removing the ignore annotation. kindly review @kdaud @sherrif10 
https://issues.openmrs.org/browse/RATEST-91

### CODE REVIEW

**Comment by kdaud** [comment]
> The test passes very well with only removing the ignore annotation.

@insookwa have you simulated this on both `true` & false instances of `firefox` and chrome driver ?

**Comment by HerbertYiga** [comment]
@insookwa does this flow as required on testing with a running openmrs instance?

**Comment by insookwa** [comment]
Hello @kdaud I have tested this flow with all scenarios and it passed. kindly review my last push for CI

**Comment by kdaud** [comment]
@insookwa let me look through the [logs](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/517/checks?check_run_id=3469164321) and fix the test. BTW did you finish up RATEST-90 and RA-1888 ?

**Comment by mozzy11** [comment]
@insookwa  are you sure this tests run succesfully in your local enviroment ??

**Comment by kdaud** [comment]
This test is already running in master [branch](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/BookRequestAppointmentTest.java)

**Pull request closed without merging**
