### PR TITLE
2.8 x

### PR DESCRIPTION
**Pull request by jwnasambu**

### CODE REVIEW

**Comment by dkayiwa** [comment]
For the steps i gave you on the old pull request, i forgot to add that you needed to pull the latest changes after you had just switched to the master branch.
That is what you have merge conflicts.

**Comment by jwnasambu** [comment]
dkayiwa have i not resolve the merge conflict?

**Comment by dkayiwa** [comment]
1. Revert your changes
2. Switch to the master branch
3. Pull the latest upstream changes
4. Create a new branch and switch to it
5. Put in the changes
6. Create a new pull request

**Comment by jwnasambu** [comment]
dkayiwa my branch has no conflict but Travis CI could not complete the build what could be the problem?

**Pull request closed without merging**
