### PR TITLE
RATEST-74:Failing Test Ignored AddFormTests

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-74
WHAT CHANGED
    
1. Tests must inherit referenceApplicationTestBase not testBase since testBase class  servers as Parent class to ReferenceApplication class 
2. AddTestForm to inherit methods from manageForms, then Manage Forms  to inherit  all methods from Administration Page not Homepage 
3. Corresponding child tests from manage forms like edittest,and delete tests needed to be also worked upon
 cc @k-joseph  @dkayiwa  Kindly review thanks

### CODE REVIEW

**Comment by sherrif10** [comment]
Oops working on travis failure first sorry

**Comment by HerbertYiga** [comment]
@sherrif10  i see your failing logs for ci are  related to Selenium Grid ,checkout https://stackoverflow.com/questions/51708666/could-not-start-a-new-session-possible-causes-are-invalid-address-of-the-remote

and https://www.selenium.dev/documentation/en/ for some references!

**Comment by sherrif10** [comment]
Sure thanks @HerbertYiga

**Comment by sherrif10** [comment]
Hello @k-joseph  @dkayiwa  , can you help me with some recommendations , this passes locally but according to the logs , the remote webdriver which is chrome is not getting instantiating, Tried to use Selenium GRID4  which triggers every driver at startup however that didnt get me going, your help with me much appreciated thanks

**Pull request closed without merging**
