### PR TITLE
RA-1320: Deleted useless catch in AppointmentBlockPage

### PR DESCRIPTION
**Pull request by DomenicoDiLeo**
I've removed a useless catch in clickOnSave method , but I have some problem with the squash.
Can you try to squash my commits?
Thank you in advance

### CODE REVIEW

**Comment by dkayiwa** [comment]
Do you mind squashing the commits into one?

**Comment by DomenicoDiLeo** [comment]
As I sad, I've problem with squashing. Can you try to do it?

**Comment by rkorytkowski** [comment]
@dkayiwa note you can squash commits while merging directly from GitHub. See https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits 

The option is hidden under the dropdown button next to the Merge pull request...

**Comment by DomenicoDiLeo** [comment]
@dkayiwa, have you tried to squash? experienced problems?

**Pull request merged**
