### PR TITLE
Updatating artifacts to their SNAPSHOT version

### PR DESCRIPTION
**Pull request by Ruhanga**
cc: @mks-d

### CODE REVIEW

**Comment by Ruhanga** [comment]
This runs safely locally @mks-d :-)

**Comment by dkayiwa** [comment]
Looks like a draft pull request.

**Comment by Ruhanga** [comment]
I had no ticket for this and so thought of it to be more of a draft. I have rectified this to a full PR. Thank you @dkayiwa.

**Comment by mks-d** [comment]
@dkayiwa should we just let this go through and see what happens on QA Ref App?

**Comment by dkayiwa** [comment]
@mks-d looks like a good plan. 👍

**Comment by dkayiwa** [comment]
@Ruhanga are you still interested in this?

**Comment by Ruhanga** [comment]
I guess not as for now. So let me go ahead to close it. Thank you for the reminder @dkayiwa  :)

**Comment by Ruhanga** [comment]
I have just confirmed the need for this @dkayiwa. An implementation requires that bugs fixed are immediately effected on the Ref App.

**Comment by dkayiwa** [comment]
@Ruhanga so are you attending to the merge conflicts?

**Comment by Ruhanga** [comment]
Let me resolve the conflicts. Thank you @dkayiwa.

**Pull request closed without merging**
