### PR TITLE
MOO-273 Add attachments module to msf distro

### PR DESCRIPTION
**Pull request by lauravignoli**

### CODE REVIEW

**Comment by mseaton** [comment]
@lauravignoli / @k-joseph  - the pull request title implies you are trying to add attachments to the MSF distro.  This commit modifies the referenceapplication distro.  @dkayiwa FYI

**Comment by dkayiwa** [comment]
@mseaton i thought they are doing it in the msf branch

**Comment by lauravignoli** [comment]
@mseaton Yes, as @dkayiwa stated, this pull request is to merge the changes to the msf branch only.

**Comment by ssmusoke** [comment]
Just wanted to provide a comment for this. Will MSF be using a custom module for its customizations? 

Isn't it easier to create its own openmrs-distro.properties file so that it can even use modules not in the RefApp?

**Pull request merged**
