### PR TITLE
RA-904: tests for ManageProviderSchedule have been enabled and significantly refactored

### PR DESCRIPTION
**Pull request by DomenicoDiLeo**
The tests AppointmentBlocksPage.java, AddEditAppointmentBlockTest.java, ManageProviderSchedulesTest.java and DeleteAppointmentBlockTest.java have been refactored and enabled

### CODE REVIEW

**Comment by dkayiwa** [comment]
@DomenicoDiLeo RA-904 is only about the manage scheduler test. Shouldn't work in the other tests be in a different pull request?

**Comment by DomenicoDiLeo** [comment]
@dkayiwa I agree with you that the issue is _apparently_ only about that test. I say apparently for two reasons: 
a) There is no reference to the test (at least in the description field), so we can't point out which test to modify
b) The tests ManageProviderSchedulesTest.java, AddEditAppointmentBlockTest.java and DeleteAppointmentBlockTest.java exercise the system almost in the same way, as you can see (All the tests referee to AppointmentBlocksPage and create/edit/delete appointments). 
Hence, we have two options:
1) I revert AddEditAppointmentBlockTest.java and DeleteAppointmentBlockTest.java on the branch RA-904. You merge only ManageProviderSchedulesTest.java with the master and close the issue RA-904. I create a new issue for those tests and a new branch with these two classes, You merge the new branch and close the issue. 
2) We improve the description of the bug by adding also the tests that are impacted and the need for a refactor of those classes. Aside from the bug, the classes were redundant, in part their behavior overlaps (I tried to divide their responsibility to some extent).

Just a comment about point 1. In general when a bug is discovered, if it is possible, there should be an impact analysis including test basis as well. Of course, this is expensive and can be justified only for some "critical" issues. Said that the solution at point 2 is the best option to me, but I can apply also the one or other options that come in your mind :)  
Thank you

**Comment by dkayiwa** [comment]
@DomenicoDiLeo the ticket was cancelled and closed as wont fix. Does your commit mean it was not supposed to be cancelled? Or does your commit deal with something else, possibly a new ticket?

**Comment by DomenicoDiLeo** [comment]
it should have not been closed. Leave the ticket as it is. 
Tomorrow night I'opening a new ticket for all the tree tests and create a new branch named with the ID of the new ticket. 
ok?

**Comment by dkayiwa** [comment]
When you say that it should not have been closed, do you mean that you can now reproduce the reported problem?

**Comment by DomenicoDiLeo** [comment]
No, I can't. 
Juts to understand a bit further about the issue management. If I find in a test something like:
"ignored due to RA-904" as it's the case for https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/ManageProviderSchedulesTest.java
If I can enable the test again, what should I do? a new issue take its ID and create the branch?  or use the issue mentioned in the test with the ignore command. 
In the past, I used the issue id found in the ignore, if I'm not mistaken. Maybe that issue referenced a bug of test itself not a bug of a functionality exercised by the test. 
In this specific situation, the other ignored tests (Edit and Delete) had an "ignore" only without id, probably they were ignored for the same reason. 
Anyway,  please don't take me wrong. I just want to understand and act accordingly to OpenMRS development guidelines. Tell me a convenient way for going further. 
Thank you for your time :)

**Comment by dkayiwa** [comment]
@DomenicoDiLeo are you able to locate the commit or ticket from which it was ignored?

**Comment by DomenicoDiLeo** [comment]
As I said in my previous message (please take a look): ignored due to RA-904

**Comment by dkayiwa** [comment]
In that case, the commit RA-904 should only have the unignoring.
The rest of the work like refactoring, etc, should be a separate ticket.

**Comment by DomenicoDiLeo** [comment]
Ok. well since that unignoring all the tests (Manage, Add, Delete)  will make it fail over and over because they refereed to a previous implementation of the module, I'm going to open a new issue. Thank you for your clarification.

**Comment by reubenvarghese1** [comment]
@DomenicoDiLeo  Please squash the commits as per https://wiki.openmrs.org/display/docs/Pull+Request+Tips :)

**Comment by DomenicoDiLeo** [comment]
@reubenvarghese1 you don't need to merge the test cases from this branch, as @dkayiwa agreed in the former messages. I'll delete this branch tonight. Please, the branch to merge is RA-1320, there should be a pull request pending.

**Comment by DomenicoDiLeo** [comment]
Please, if you can, destroy this pull request, thus no other will be tempted to merge the code. 
Thank you.

**Comment by reubenvarghese1** [comment]
@DomenicoDiLeo  Unfortunately I do not have the necessary privileges to delete this PR.Sorry my bad. I was just doing my part of pull request reviewing and found this one open and not following the PR tips. Feel free to ignore the previous comment  :)

**Comment by dkayiwa** [comment]
Ok destroyed as instructed 😊

**Comment by dkayiwa** [comment]
@reubenvarghese1 great job. Keep it up! 👍

**Comment by reubenvarghese1** [comment]
Thanks @dkayiwa  :-)

**Pull request closed without merging**
