### PR TITLE
Switch reporting compatibility to version 2.0.9-SNAPSHOT

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud looks like you again gave up on the platform tests guy.

**Comment by kdaud** [comment]
> @kdaud looks like you again gave up on the platform tests guy.

have been squeezed up for this week and couldn't make it. Will do those guy on Saturday night + Sunday to have them pulled off from the pending task list.

**Comment by dkayiwa** [comment]
@kdaud those tests are of a higher priority than what you are doing now. I wonder why you keep pushing them further. Sign of a C...

**Comment by kdaud** [comment]
will have this closed in favor of pull/612

**Pull request closed without merging**
