### PR TITLE
RATEST-257:Remove selenium legacy Tests and Pages

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-257

### CODE REVIEW

**Comment by kdaud** [comment]
@sherrif10 where is the ticket that will track this commit that has significant changes to the repo?

**Comment by sherrif10** [comment]
Which commit ?

**Comment by sherrif10** [comment]
As you have seen, this changes remove both the pages and tests, what we are
remaining with is to cater for all the selenium tests.

And I think handling selenium tests, it would be quite better of we have
RATEST-240 , get merged otherwise the ticket is going to be huge to handle,
I tried that last night but it need a separate way of handling especially
in its own ticket alone

**Comment by kdaud** [comment]
@sherrif10 is the ticket ID attached any where in this PR?

**Comment by sherrif10** [comment]
> is the ticket ID attached any where in this PR?

https://issues.openmrs.org/browse/RATEST-257

**Comment by sherrif10** [comment]
@kdaud  waiting for approve

**Comment by dkayiwa** [comment]
@sherrif10 can you look into these merge conflicts?

**Pull request closed without merging**
