### PR TITLE
RA-1818:Revert openmrsVersion From 2.4.0-SNAPSHOT to 2.3.0 for REF-APP 2.11.0

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RA-1818

cc @dkayiwa  @mozzy11

### CODE REVIEW

**Comment by tendomart** [comment]
@sherrif10  do you think the mode Snapshot versions need reverting as well ?

**Comment by sherrif10** [comment]
Yes thanks @tendomart , will create a ticket for that after confirming that those are the modules that need to be released, remember currently those snapshots are not stable, until they are stable and we make them ready for release by updating them without -SNAPSHOT

**Comment by mozzy11** [comment]
ok thanks @sherrif10 .

**Comment by dkayiwa** [comment]
Is there any reason why you are not using this? https://github.com/openmrs/openmrs-core/tree/2.3.1

**Comment by mozzy11** [comment]
cc @sherrif10   ,can you make a new PR for that ??

**Comment by sherrif10** [comment]
We can revert it to 2.3.1, am making a follow-up commit

**Comment by sherrif10** [comment]
Followup commit https://github.com/openmrs/openmrs-distro-referenceapplication/pull/273

**Comment by mozzy11** [comment]
am reverting this PR, still looking into details why the standalone build fails at https://ci.openmrs.org/browse/REFAPP-OMODDISTRO-TS-10273/log .

Its releated to liquibase upgrade in the core

**Comment by sherrif10** [comment]
@dkayiwa  @mozzy11  Error logs breakage here https://pastebin.com/FMTeVuX3, so how do we track that down in core, i see we need to keen because it may even not in core

**Pull request merged**
