### PR TITLE
RATEST-189: Refactor distro tests code indention for quality assurance

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-189)

Description -> Refactor distro tests code indention for quality assurance

### CODE REVIEW

**Comment by kdaud** [comment]
Waiting for review!
cc: @sherrif10

**Comment by sherrif10** [comment]
Thanksi think before  we can merge any identation commits , we need to make sure code format convention is systematic and similar with all the code with in this tests, i would love to hear from @dkayiwa  @ibacher  about this kind of formatting because i think a number of tests are not having the same openmrs formatter especially with this module

**Comment by kdaud** [comment]
> We need to make sure code format convention is systematic and similar with all the code with in this tests, 

Here are 8 test file samples of OpenMRS files within [openmrs-distro-referenceapplication](https://github.com/openmrs/openmrs-distro-referenceapplication)
1. [AddPatientAppointmentTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/AddPatientAppointmentTest.java) from openmrs-core
2. [MergeVisitTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/MergeVisitsTest.java) from distro-referenceapplication
3. [EditDemographicTestt](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/EditDemographicTest.java) from openmrs-module-appui
4. [ClinicianFacingPatientDashboardPage](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/page/ClinicianFacingPatientDashboardPage.java) from distro-referenceapplication.
5.  [UsingBackButtonInMergePatientTest.](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/UsingBackButtonInMergePatientTest.java)
6. [SearchActiveVisitsTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/SearchActiveVisitsTest.java)
7. [EditDemographicTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/EditDemographicTest.java)
8. [EndVisitTest](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/EndVisitTest.java)

Currently AddEditAppointmentBlockTest indention looks like [this](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/master/ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java) in master But after formatting as addressed in this PR the file is now formatted to this [indention.](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/9f83ae9b92b23d41d9eb738cf85b771e5fef8d84/ui-tests/src/test/java/org/openmrs/reference/AddEditAppointmentBlockTest.java) 
cc: @sherrif10

**Comment by kdaud** [comment]
All the tests in distro that were not properly indented have been addressed in this commit.
cc: @sherrif10 @dkayiwa

**Pull request merged**
