### PR TITLE
Revert Distro OpenMRS Distro 2.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by tendomatGitHub**
@dkayiwa Can you please revert OpenMRS Distro version from 2.8.0-SNAPSHOT to 2.7.0SNAPSHOT,so i can resume with release.Thanks alot

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the merge conflicts? You need to start by updating your fork with the latest upstream changes.

**Comment by dkayiwa** [comment]
Did you see the merge conflicts? You need to start by updating your fork with the latest upstream changes.

**Comment by tendomatGitHub** [comment]
Had done so at git and thought everything was up to date.

**Comment by tendomatGitHub** [comment]
@dkayiwa i fixed the conflict,but now checks are failing.there is no conlusive reason here

**Pull request closed without merging**
