### PR TITLE
GCI-4 - Manage Users Test

### PR DESCRIPTION
**Pull request by Izaron**
Manage Users Test

Ticket: https://issues.openmrs.org/browse/GCI-4: 
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/4630092420481024
YouTube Video: http://youtu.be/vJAXKMwN25Y

Five tests: clerk role, doctor role, nurse role, sysadmin role, rename user. (All roles is Organizational, as they combine other basic role)

### CODE REVIEW

**Comment by harsha89** [comment]
Looks good!

**Comment by k-joseph** [comment]
@harsha89, did we forget any PR that had no conflicts? this one has been merged into master directly

**Comment by robbyoconnor** [comment]
hrm...okay I'm confused...there was no record on the PR...if you merge it...close the PR or mark it in some way

**Comment by robbyoconnor** [comment]
I reverted this merge -- We can manually add it back.

**Pull request merged**
