### PR TITLE
RA-980: fixed VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, and AddRolesToUserTest 

### PR DESCRIPTION
**Pull request by zak905**
Refractored VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, AddRolesToUserTest according to Guidelines in : https://issues.openmrs.org/browse/RA-980
Subtasks: 
https://issues.openmrs.org/browse/RA-1078
https://issues.openmrs.org/browse/RA-1079
https://issues.openmrs.org/browse/RA-1080

### CODE REVIEW

**Comment by dkayiwa** [comment]
@zak905 the ticket says you should create a sub task for each test you are going to fix. Did you do that?
Then also remember to take note of https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by zak905** [comment]
@dkayiwa Yes, I did. I added the links to the description. I also closed the old ticket as advised in the tips.

**Comment by dkayiwa** [comment]
@zak905 can you git the claim for development button for these tickets?

**Comment by dkayiwa** [comment]
@zak905 If you see that the test is not annotated with @Category(BuildTests.class) then it must be fixed. You do not seem to have fixed any of these tests.

**Comment by zak905** [comment]
@dkayiwa what do you mean ? I did add @category in all of them. Check out the @test method. The @category annotation is at the level of the method and not the class. 

https://github.com/openmrs/openmrs-distro-referenceapplication/pull/112/files

**Comment by dkayiwa** [comment]
@zak905 from the instructions, "If you see that the test is not annotated with @Category(BuildTests.class) then it must be fixed", my understanding is that you first fix before adding Category. But i see that you just added Category without fixing anything.

**Comment by zak905** [comment]
@dkayiwa other than the @category annotation and the license that was added at the beginning, the rest  comply with the rules. I cannot fix more than that.

**Comment by dkayiwa** [comment]
@zak905 so does this mean that the test was failing only because of lack of the license?

**Comment by zak905** [comment]
@dkayiwa I like the sarcasm. 

As I said, I followed the rules at https://wiki.openmrs.org/display/docs/Automated+Testing+Guidelines

No more, no less. If there is only one thing that is missing(e.g lisense, annotation, number of steps...) , then the test is said to be needing a fix. Even if the test passes very well, it needs a fix to comply with the rules. clear?

**Comment by dkayiwa** [comment]
@zak905 i get it. :)
So can you now claim the three tickets?

**Comment by zak905** [comment]
@dkayiwa I just did.

**Comment by dkayiwa** [comment]
@zak905 i have reverted because of https://ci.openmrs.org/browse/REFAPP-OMODDISTRO-4514

**Comment by zak905** [comment]
@dkayiwa I don't see where the issue is. I can't do anything for now

**Comment by yancmo** [comment]
Have you tried running the tests locally? You didn't fix anything, adding comments and adding a @Test annotation won't change anything, except to run a broken test. The problem with current unconverted tests is, when tests navigate through pages and call "waitForElement()" or "waitForPage()" it'll timeout. What you'll have to do is modify pages such that when a new page is visited, it'll return a new instance of a page. Something similar to guideline 8) where ActiveVisitsPage activeVisitsPage = homePage.goToActiveVisitsSearch();
If it were that simple, anyone could have fixed all tests within an hour.

**Pull request merged**
