### PR TITLE
 Please Revert OpenMRS Distro from 2.8.0-SNAPSHOT to 2.7.0-SNAPSHOT 

### PR DESCRIPTION
**Pull request by tendomatGitHub**
@dkayiwa Please look into this and see if it is valid for you to Revert OpenMRS Distro from 2.8.0-SNAPSHOT to 2.7.0-SNAPSHOT

### CODE REVIEW

**Comment by dkayiwa** [comment]
@tendomatGitHub you forgot to change this in a pom file or two more.

**Comment by tendomatGitHub** [comment]
@dkayiwa so you mean i alter other pom's?

**Comment by dkayiwa** [comment]
Every instance of 2.8.0-SNAPSHOT

**Comment by tendomatGitHub** [comment]
Alright

**Pull request closed without merging**
