### PR TITLE
Refractored 3 tests according to Guidelines

### PR DESCRIPTION
**Pull request by zak905**
Refractored VisitTypeAdministrationTest, XSSOnPhoneNumberFieldTest, AddRolesToUserTest: 

Added @Category
Added License at the beginning
Checked the rules at https://wiki.openmrs.org/display/docs/Automated+Testing+Guidelines which seems to comply.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@zak905 is this work for the sub tasks of https://issues.openmrs.org/browse/RA-980?
If yes, i would expect the ticket number in commit message as advised at https://wiki.openmrs.org/display/docs/Pull+Request+Tips
I would also expect you to claim those tickets and add a pull request url to each.
The guideline says that tickets which do not have category need to get fixed. Did these get fixed before you added the category?

**Comment by dkayiwa** [comment]
@zak905 are you still interested in finishing this up?

**Comment by zak905** [comment]
@dkayiwa It is about the subtasks. I created 3 subtasks and put the pull requests in the description

 I did not create all of them, only the first 3 are mine. Some other people are working on other sub, so I think it is better if only the subtasks are assigned not the whole tickets. 

I can close this pull request, and create another one with the name of the ticket as a title. Sounds good?

**Comment by dkayiwa** [comment]
@zak905 sounds good 👍

**Pull request closed without merging**
