### PR TITLE
Revert "(release-revert) revert to dev versions"

### PR DESCRIPTION
**Pull request by ibacher**
Reverts openmrs/openmrs-distro-referenceapplication#765

### CODE REVIEW

**Comment by vasharma05** [comment]
Why are we reverting the changes?

**Comment by ibacher** [comment]
@vasharma05 Not enough changes were made. Specifically, the Maven version needs to be changed on the release commit.

**Comment by vasharma05** [comment]
What is the Maven version to be changed?

Is it 2.6.3, or a new release is needed for openmrs-core?
Thanks!

image

**Comment by ibacher** [comment]
@vasharma05 It's the version of the Maven artifact that is this repo (the POM.xml files)

**Pull request merged**
