### PR TITLE
Updated Distro pom.xml to latest module versions as of 2.7

### PR DESCRIPTION
**Pull request by tendomatGitHub**
@ssmusoke  , @raff Can you please review this and see if i need to add anything ,thanks

### CODE REVIEW

**Comment by tendomatGitHub** [comment]
@dkayiwa can you please review this..Branch has no conflicts but the checks fail..
I added addresshierarchy module but did not include the api,test and omod dependencies.

**Comment by dkayiwa** [comment]
@tendomatGitHub did you look at the travis error log?

**Comment by tendomatGitHub** [comment]
@dkayiwa  yes but there is no ruled out error..been reding through

**Comment by dkayiwa** [comment]
Do you get any error when you compile those changes locally?

**Comment by tendomatGitHub** [comment]
@dkayiwa No i do not get any errors .The builds are succesful.So am wondering what the problem could be

**Comment by tendomatGitHub** [comment]
@dkayiwa  iv'e run "mvn clean install" many times prior to this commit and the builds were successful.

**Pull request merged**
