### PR TITLE
 edited pom

### PR DESCRIPTION
**Pull request by jwnasambu**

### CODE REVIEW

**Comment by jwnasambu** [comment]
This is the current edited root pom.xml

**Comment by dkayiwa** [comment]
Can you close those pull requests that are no longer relevant?

**Comment by jwnasambu** [comment]
I have closed them

**Comment by dkayiwa** [comment]
The commit message or pull request description should have been something like "switch to the 2.8 release versions of modules"

**Comment by dkayiwa** [comment]
Now that this is merged, in preparation to the next step of deploying to the uat-refapp server, do you have access to bamboo?

**Comment by jwnasambu** [comment]
yes i have acess

**Comment by dkayiwa** [comment]
When you go here https://ci.openmrs.org/deploy/selectVersionForExecute.action?environmentId=93126669&returnUrl=/deploy/viewDeploymentProjectEnvironments.action?id=93650946 do you see the "Start deployment" button?

**Comment by jwnasambu** [comment]
yes i have seen the "start deployment" button

    On Sunday, June 17, 2018, 10:44:54 PM GMT+3, dkayiwa <notifications@github.com> wrote:  
 
 
When you go here https://ci.openmrs.org/deploy/selectVersionForExecute.action?environmentId=93126669&returnUrl=/deploy/viewDeploymentProjectEnvironments.action?id=93650946 do you see the "Start deployment" button?

**Comment by jwnasambu** [comment]
I have seen the "start deployment" button.

**Comment by jwnasambu** [comment]
I started deployment and this is the result "Success: Deployment of Reference-Application-2.8.0 to UAT refapp (dockerhub)"

**Comment by dkayiwa** [comment]
We cannot deploy when the reference application distro is still failing.

**Comment by jwnasambu** [comment]
oooh so sorry

**Comment by dkayiwa** [comment]
After fixing the failures, i have done a deployment on uat-refapp
So you can now proceed with the testing process. Hopefully you still remember what to do as agreed upon on that project management call which you attended.

**Comment by jwnasambu** [comment]
Thanks for fixing the travis ci. I may not remember as i had confided in you, i was getting what was discussed as much as you people were getting me.

    On Monday, June 18, 2018, 1:30:05 AM GMT+3, dkayiwa <notifications@github.com> wrote:  
 
 
After fixing the failures, i have done a deployment on uat-refapp
So you can now proceed with the testing process. Hopefully you still remember what to do as agreed upon on that project management call which you attended.

**Comment by dkayiwa** [comment]
Invite people to test and give comments in regards to bugs discovered or any other form of feedback.
Burke suggested a url like this one which gives people as screen to log in and then directly type feedback in the notes page on the right hand side: http://burkeware.com/feedback/index.html?left=https://uat-refapp.openmrs.org/&right=https://notes.openmrs.org/feedback-example&title=Example+feedback

**Comment by dkayiwa** [comment]
In your communication, remember to state that the testing window is only one week from the time of your post (explicitly specify the start and end date). After which, if no bugs have been discovered, you will go ahead and immediately release.

**Pull request merged**
