### PR TITLE
RATEST-155:Failing Test : Fix AddUserRoles

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-155  cc @k-joseph

### CODE REVIEW

**Comment by kdaud** [comment]
Fix the build at https://github.com/openmrs/openmrs-distro-referenceapplication/pull/507/checks?check_run_id=3079450149

**Comment by sherrif10** [comment]
This work is in progress thank you

**Comment by kdaud** [comment]
@sherrif10 any suggestion on this PR ?

**Comment by sherrif10** [comment]
Sorry this should be closed since you are working on it here  https://github.com/openmrs/openmrs-distro-referenceapplication/pull/563

**Comment by kdaud** [comment]
> Sorry this should be closed since you are working on it

I put on hold working on that test because I realized its fix seems not to be within the test But within the system that fails the validation process. At the moment the ticket is ready for work as of now am occupied with other tasks.

**Comment by sherrif10** [comment]
Sure no problem please

**Pull request closed without merging**
