### PR TITLE
O3-2996: Add billing module to openmrs distro pom file and spa config

### PR DESCRIPTION
**Pull request by alaboso**
## Description of what I changed

This PR is to introduce the Billing and StockManagement modules to the reference application. Billing requires Stock Management as a dependency. It replaces [this PR.](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/842)

- Added stock management backend module (+ roles and privileges)
- Added billing backend module (+ metadata)
- Added stock management frontend module
- Added billing frontend module
- Renamed DemoQueueConcepts - Clinical consultation to Clinical Consult
- Updated initializer version from `2.7.0` to `2.8.0-SNAPSHOT` - (bug fix for privileges and roles bug)
- Updated openmrs-packager-maven-plugin from `1.7.0` to `1.9.0-SNAPSHOT` - to use openconceptlab module version `2.4.0`

## Issue I worked on

https://openmrs.atlassian.net/browse/O3-2996

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

`mvn --batch-mode --update-snapshots --activate-profiles distro,validator clean package`

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ODORA0** [comment]
@dkayiwa PR For your Review

**Comment by dkayiwa** [comment]
@ODORA0 did you get a chance to look into the merge conflicts?

**Comment by alaboso** [comment]
> @ODORA0 did you get a chance to look into the merge conflicts?

@dkayiwa  - As of the time of making this PR, there was no merge conflict. @eudson @ODORA0

**Review by dkayiwa — APPROVED** [review]

**Comment by dkayiwa** [comment]
@alaboso @ODORA0 the log is filled with so many exception that look like this: https://pastebin.com/R6cvEiRU
Can you look into them?

**Comment by alaboso** [comment]
@ODORA0  is looking into this and will issue an update

**Comment by dkayiwa** [comment]
> @ODORA0 is looking into this and will issue an update

Thanks! I look forward to reviewing and testing it again. 😊

**Comment by ibacher** [comment]
The issue here is really straight-forward: the AOP controller [assumes that `Utils.getDefaultLocation()`](https://github.com/openmrs/openmrs-module-billing/blob/4d8c0408c641f88779e89a4a2e1a1b27295d1d65/api/src/main/java/org/openmrs/module/billing/advice/GenerateBillFromOrderAdvice.java#L80) returns a valid object whereas [`Utils.getDefaultLocation()` can explicitly return `null`](https://github.com/openmrs/openmrs-module-billing/blob/4d8c0408c641f88779e89a4a2e1a1b27295d1d65/api/src/main/java/org/openmrs/module/billing/util/Utils.java#L76).

By itself, this should be solvable using simple metadata to define the missing GP.

A couple of comments on the design here:

1. Why would we use a GP instead of a Location Tag ("Default Cashpoint" or something)?
2. The code doesn't seem to actually do anything useful with that value (or the `cashierUUID`) so it's unclear to me why it's defined at all (it's always passed to `addBillItemToBill()`, but that function does nothing with it)
3. It's really weird to me that we assume that the active user is the cashier when the event we're handling is an order being placed, so the active user is the _provider placing the order_. But maybe this is just a badly named field?
4. What's the point of the CashPoint class rather than, again, just tagging a specific location as a CashPoint?

**Comment by alaboso** [comment]
@dkayiwa  @ibacher  - The issue has been fixed and a new artifact published. Is it ok to re-run, manually, the distro CI to redeploy to dev3? I can trigger it

**Comment by ibacher** [comment]
We really should release versions of those modules and have the ref app depend on the releases.

**Comment by dkayiwa** [comment]
@alaboso i have tested your changes and confirmed that we no longer have the former startup exceptions. Thanks for looking into this.

**Pull request merged**
