### PR TITLE
Bundle Client registry

### PR DESCRIPTION
**Pull request by sherrif10**
Ticket  https://openmrs.atlassian.net/browse/HIE-7

 cc @samuelmale @dkayiwa

### CODE REVIEW

**Comment by sherrif10** [comment]
Hello @samuelmale . Do we really need to bundle this client registry. i want to say that am following the older process, Not quite sure if its the same proccess since we are running on 03 branch.

**Comment by tendomart** [comment]
wonder why it's complaining of `1.1.8-SNAPSHOT`

**Comment by tendomart** [comment]
@sherrif10  i think this is for the backend support.

**Comment by tendomart** [comment]
I think no version was released to JFROG, that's why it's complaining

**Comment by sherrif10** [comment]
Yes @tendomart .Thats right.

**Comment by samuelmale** [comment]
@sherrif10 unfortunately I don't think we are yet to the point of bundling this module in the refApp

**Comment by sherrif10** [comment]
Thanks, i will close this for now.

**Pull request closed without merging**
