### PR TITLE
RATEST-200: Set the true element reference for city_field with in manage locations page

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [ID](https://issues.openmrs.org/browse/RATEST-200)

Description -> Set the true element reference for city_field with in manage locations page

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud can you remind me about the test which is failing and will be fixed after merging this?

**Comment by kdaud** [comment]
@dkayiwa here we [go-->](https://github.com/openmrs/openmrs-distro-referenceapplication/pull/535#issuecomment-921817311)

**Comment by dkayiwa** [comment]
I mean a failing CI build

**Comment by kdaud** [comment]
> I mean a failing CI build

Have just written a new test called [Location-Test ](https://issues.openmrs.org/browse/RATEST-200) whose PR is not yet pushed to the [repo](https://github.com/openmrs/openmrs-contrib-qaframework) since its page functionalities were missing in distro, so at the moment we do not have build failures.

**Pull request merged**
