### PR TITLE
O3 3903:Add ability to Override Page Title and Favicon in O3 Distributions

### PR DESCRIPTION
**Pull request by tendomart**
This is a Draft PR for adding ability to Overide Page Title and Favicon in O3 Distibutions

https://openmrs.atlassian.net/browse/O3-3903
Screenshot from 2024-09-10 23-29-01

Hi @ibacher  @michaelbontyes  @rbuisson @vasharma05  please look at this progress

### CODE REVIEW

**Comment by michaelbontyes** [comment]
Thank you @tendomart. Is there a reason why it is configured twice in the front end config and in the docker compose environment values? Can you also modify the favicon using front end config?

**Comment by tendomart** [comment]
@michaelbontyes  that was my source of confusion as to which file takes precedence over configured values.

As for the favicon, been working on adding that, and best place would be the /distro folder as long as anyone can place the right dimensions of any favicon.ico resource

**Comment by jnsereko** [comment]
> As for the favicon, been working on adding that, and best place would be the /frontend folder as long as anyone can place the right dimensions of any favicon.ico resource

I personally think this should be added in [esm core](https://github.com/openmrs/openmrs-esm-core), like the [logo configuration](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/apps/esm-login-app/src/config-schema.ts#L58), basing on the fact that some implementors are using the OpenMRS SDK.
cc @dkayiwa

**Comment by tendomart** [comment]
Thanks @ibacher it was aimed at making Page Title / Favicon overridable in O3 Refapp Distros

**Comment by tendomart** [comment]
@dkayiwa  this is the one that requires clear direction of keeping this under Distro or moving it to esm-core

**Comment by dkayiwa** [comment]
> @dkayiwa this is the one that requires clear direction of keeping this under Distro or moving it to esm-core

**Comment by dkayiwa** [comment]
@tendomart i thought the direction was given to you, but you are simply blocked by how to implement it?

**Comment by tendomart** [comment]
Yes Iam blocked. @dkayiwa

**Comment by dkayiwa** [comment]
Where exactly are you blocked?

**Comment by tendomart** [comment]
Making the default Favicon overridable with a custom one.

**Comment by brandones** [comment]
> is it the same issue that was achieved at https://github.com/openmrs/openmrs-esm-core/commit/77459605fd51c84db44af7dd462452fdb5670c7b ?
> 
> following this ticket https://openmrs.atlassian.net/browse/O3-412

Yes. You should be able to set the page title using the `--page-title` argument to `yarn openmrs build`.
 
> and is so, which files do we have to configure in any distro to achieve the same in esm core ?

I don't understand the question.

**Pull request closed without merging**
