### PR TITLE
(release) Release 3.0.0-beta.17

### PR DESCRIPTION
**Pull request by jayasanka-sack**
Use this sheets to check versions, tags and release PRs of apps:
https://docs.google.com/spreadsheets/d/1vAZ-mFIjaHdLkxUPL869StdhcPeVkPjmCF3rUpfLErw/edit#gid=0

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
Two things,

1. The E2E job is failing during the build as esm-home v5.2.1 has not published to the registry. 
   Even pre releases aren't published : https://www.npmjs.com/package/@openmrs/esm-home?activeTab=versions
   Failing esm-home build: https://www.npmjs.com/package/@openmrs/esm-home?activeTab=versions
2. It seems "Build and Validate Configuration" job isn't properly running. There's a warning message in the logs.

**Comment by ibacher** [comment]
Re 1: 

* In [CI](https://github.com/openmrs/openmrs-esm-home/blob/33b3e2648a1591ae6ea62097b8d015f03018d12f/.github/workflows/node.js.yml#L87) during the pre-publish, we run: `yarn workspaces foreach --worktree --topological --exclude @openmrs/esm-home ...`.
* In `ci:publish` in package.json, we run: `yarn workspaces foreach --all --topological --exclude @openmrs/esm-home ...`
* In `ci:prepublish` in package.json, we run: `yarn workspaces foreach --all --topological --exclude @openmrs/esm-home ...`

`--exclude` means that we're telling `yarn` not to run those commands in that package... but that's the only package in the monorepo, so effectively we're running a really complicated command to say "do nothing". In all of those cases, we need to remove the `--exclude`.

Re 2: Yeah the step needs to be updated to run `mvn --batch-mode --update-snapshots --activate-profiles distro,validator clean package`. Sloppy change on my part.

**Comment by jayasanka-sack** [comment]
Resolved issue 1 here: https://github.com/openmrs/openmrs-esm-home/pull/182

The repo do contain packages directory and we need to exclude `@openmrs/esm-home`. The one we need to publish is `@openmrs/esm-homeesm-home-"app"` 

Btw, I was wrong about pre releases as I was looking in the wrong package in the registry (I was looking for "home". not the "home-app")

**Comment by befantasy** [comment]
Excuse me, are you still not planning to pull and update the language files from Transifex in the beta 17 release?
I don't quite understand. If the Github Action synchronization script still doesn't work properly, why can't we manually force-pull the language files and then submit a pull request to the project? 

I previously used the tx tool to pull the Chinese language files from Transifex and submitted a pull request, but for some reason, it hasn't been approved yet. https://github.com/openmrs/openmrs-esm-patient-chart/pull/1615  （outdated now)

I really hope that the latest Chinese language files can be included in the beta 17 release.

**Comment by jayasanka-sack** [comment]
@befantasy, I'm truly sorry to hear about the situation. I understand how frustrating it must be. Given that the patient chart has already been released it's challenging to make further changes at this point. With beta 18 scheduled to start in two weeks, we can include changes to it.

Your efforts on translations mean a lot to us. Thank you for your understanding and continued support. ❤️

**Review by ibacher — APPROVED** [review]

**Pull request merged**
