### PR TITLE
(fix) Fix mapping errors when adding SOAP note concepts

### PR DESCRIPTION
**Pull request by CynthiaKamau**
This pr is dependent on [this](https://github.com/mekomsolutions/openmrs-module-initializer/pull/274) pr in the initializer

### CODE REVIEW

**Comment by dkayiwa** [comment]
@CynthiaKamau when i apply the changes in this pull request, this is what i get in the logs: https://pastebin.com/dLvmccCU

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau when i apply the changes in this pull request, this is what i get in the logs: https://pastebin.com/dLvmccCU

This [pr](https://github.com/mekomsolutions/openmrs-module-initializer/pull/274) will sort that out

**Comment by dkayiwa** [comment]
> This [pr](https://github.com/mekomsolutions/openmrs-module-initializer/pull/274) will sort that out

I am already using version 2.3.0 of the openconceptlab module: https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/pom.xml#L36

**Comment by CynthiaKamau** [comment]
> > This [pr](https://github.com/mekomsolutions/openmrs-module-initializer/pull/274) will sort that out
> 
> I am already using version 2.3.0 of the openconceptlab module: https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/pom.xml#L36



> > This [pr](https://github.com/mekomsolutions/openmrs-module-initializer/pull/274) will sort that out
> 
> I am already using version 2.3.0 of the openconceptlab module: https://github.com/openmrs/openmrs-distro-referenceapplication/blob/main/distro/pom.xml#L36

@dkayiwa i have fixed the mapping errors from the soap note

**Comment by dkayiwa** [comment]
@CynthiaKamau this is what i get after running these changes on a fresh installation: https://pastebin.com/YzJ2UphK

**Comment by CynthiaKamau** [comment]
> https://pastebin.com/YzJ2UphK

Those seem to originate from `drugs_concepts-core_demo.csv` if im not wrong

**Comment by alaboso** [comment]
@CynthiaKamau  - There were some failing tests regarding patientmanagement but after a re-run, it passed and all is green now. @dkayiwa what do you think?

**Comment by dkayiwa** [comment]
> Those seem to originate from `drugs_concepts-core_demo.csv` if im not wrong

@alaboso what do you say about this?

**Comment by alaboso** [comment]
> > Those seem to originate from `drugs_concepts-core_demo.csv` if im not wrong
> 
> @alaboso what do you say about this?

There were some drug concepts in the `openmrs_SOAP_vSOAP_Note_autoexpand-SOAP_Note.2024-07-27_070529.zip` that were also in the default `drugs_concepts-core_demo.csv` - We have since removed them from the OCL zip file in favor of those in the default distro csv. @dkayiwa @CynthiaKamau

**Comment by dkayiwa** [comment]
I have tested and confirmed that all is now well. Thanks @CynthiaKamau and @alaboso 👍

**Review by dkayiwa — APPROVED** [review]

**Pull request merged**
