### PR TITLE
(chore) Release `3.0.0-beta.11`

### PR DESCRIPTION
**Pull request by vasharma05**
Releasing the beta.11 version for the refapp, since the version `3.0.0-beta.10` failed due to the incorrect version for the @openmrs/esm-system-admin-app.

### CODE REVIEW

**Comment by ibacher** [comment]
We have a very strict convention for the name of release commits, please follow that (pretty much exactly the commit messages from the last PR with the version changed).

**Comment by ibacher** [comment]
We do need a “release-revert” commit too.

**Comment by ibacher** [comment]
Also, the version in the Pom.xml files should reflect beta.11

**Comment by vasharma05** [comment]
Yes @ibacher !
I wanted to test the build checks before pushing the release-reverse commit.

**Review by ibacher — APPROVED** [review]

**Pull request merged**
