### PR TITLE
Switch qa server to run on the latest modules SNAPSHOT version

### PR DESCRIPTION
**Pull request by kdaud**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kdaud use one pr for all these guys.

**Comment by kdaud** [comment]
Would wish to have these guys enter master plan.

**Comment by dkayiwa** [comment]
Why only these 4?

**Comment by sherrif10** [comment]
A ticket  in jira that will track these changes as well will also suffice.

**Comment by dkayiwa** [comment]
These are minor changes that do not require a jira ticket.

**Comment by kdaud** [comment]
Will open this guy if desirable!

**Pull request closed without merging**
